build: Add zig build system support
kiennq/scoop-better-shimexe pull request #10
Opened 2024-03-30 03:19 UTC by chawyehsu

In my case it's eaiser to build it with zig build. And it's also easier to cross build for Windows ARM.

2024-04-24 00:11 UTC, kiennq commented
Thanks, can you move the `build.ps1` and `build.zig` to the `zig` folder?

2024-07-05 09:16 UTC, seiya-git requested changes

2024-10-26 02:38 UTC, chawyehsu commented on shim.cpp
> +#include <corecrt.h>
I noticed that, I changed it as there's no `corecrt_wstdio.h` header available in mingw-w64. I don't know the proper way to port this line of code yet.

2024-10-30 19:37 UTC, kiennq commented
Thanks for your PR.

2024-10-30 19:37 UTC, merged